export const DEFAULT_LANDING_PAGE_SETTINGS = {
  landingVersion: 'v2',
  bannerActive: true,
  bannerTextEn: '',
  bannerTextEs: '',
  topBarTextEn: '',
  topBarTextEs: '',
  heroKickerEn: 'PEPTIDES COSTA RICA',
  heroKickerEs: 'PEPTIDES COSTA RICA',
  heroTitleEn: 'Premium Peptides in Costa Rica',
  heroTitleEs: 'Péptidos premium en Costa Rica',
  heroSubEn: 'Your local source for premium, research-grade peptide products with reliable delivery.',
  heroSubEs: 'Tu fuente local de péptidos premium de grado investigación con entrega confiable.',
  heroTextEn: 'We combine verified quality, transparent pricing, and local Costa Rica logistics so ordering is clear from product selection to delivery.',
  heroTextEs: 'Combinamos calidad verificada, precios transparentes y logística local en Costa Rica para que ordenar sea claro de principio a fin.',
  heroImageUrl: '/catalog-promo-banner.webp',
  heroDropdownLabelEn: 'What are you looking for?',
  heroDropdownLabelEs: '¿Qué estás buscando?',
  heroDropdownPlaceholderEn: 'Choose a quick action',
  heroDropdownPlaceholderEs: 'Elige una acción rápida',
  heroDropdownOptions: [
    { labelEn: 'Shop by product', labelEs: 'Comprar por producto', href: '/catalog' },
    { labelEn: 'Shop by goal', labelEs: 'Comprar por objetivo', href: '/catalog' },
    { labelEn: 'View COA library', labelEs: 'Ver biblioteca COA', href: '/info-center#coa-library' },
    { labelEn: 'Ask on WhatsApp', labelEs: 'Preguntar por WhatsApp', href: 'whatsapp' },
  ],
  primaryCtaEn: 'Browse All Peptide Products',
  primaryCtaEs: 'Ver todos los productos',
  secondaryCtaEn: 'Order on WhatsApp',
  secondaryCtaEs: 'Ordenar por WhatsApp',
  catalogBannerActive: true,
  catalogBannerImageUrl: '/catalog-promo-banner.webp',
  catalogBannerUrl: '/catalog',
  catalogBannerAltEn: 'Peptides Costa Rica product vials',
  catalogBannerAltEs: 'Viales de Peptides Costa Rica',
  pressActive: true,
  pressTitleEn: 'Peptides Costa Rica Was Featured In The Costa Rica News.',
  pressTitleEs: 'Peptides Costa Rica fue destacado en The Costa Rica News.',
  pressCtaEn: 'Read the article',
  pressCtaEs: 'Leer el articulo',
  pressUrl: 'https://thecostaricanews.com/introducing-peptides-costa-rica-bringing-trusted-peptide-products-to-costa-rica/',
  pressLogoUrl: '/costa-rica-news-logo.png',
  differenceTitleEn: 'We Do Things Differently',
  differenceTitleEs: 'Hacemos las cosas diferente',
  differenceTextEn: 'Clear pricing, bulk discounts, direct communication, and reliable local service inside Costa Rica.',
  differenceTextEs: 'Precios claros, descuentos por volumen, comunicación directa y servicio local confiable dentro de Costa Rica.',
  differenceCards: [
    {
      titleEn: 'No cross-border delays',
      titleEs: 'Sin demoras de aduana',
      textEn: 'Inventory is already in Costa Rica, reducing international shipping uncertainty.',
      textEs: 'El inventario ya está en Costa Rica, reduciendo la incertidumbre del envio internacional.',
    },
    {
      titleEn: 'Fast, safe online ordering',
      titleEs: 'Ordenes rápidas y seguras',
      textEn: 'A streamlined checkout and WhatsApp support help customers order with confidence.',
      textEs: 'Un checkout simple y soporte por WhatsApp ayudan a ordenar con confianza.',
    },
    {
      titleEn: 'No hidden import fees',
      titleEs: 'Sin cargos ocultos de importación',
      textEn: 'Local coordination keeps the buying process predictable and straightforward.',
      textEs: 'La coordinación local mantiene el proceso claro y predecible.',
    },
    {
      titleEn: 'Clear access and professional service',
      titleEs: 'Acceso claro y servicio profesional',
      textEn: 'Product, COA, payment, and delivery questions are answered directly.',
      textEs: 'Respondemos directamente preguntas de producto, COA, pago y entrega.',
    },
  ],
  offerTitleEn: 'What We Offer',
  offerTitleEs: 'Qué ofrecemos',
  offerTextEn: 'Peptides are studied for specific effects in the body and researched for how they interact with signaling pathways.',
  offerTextEs: 'Los péptidos se estudian por efectos específicos en el cuerpo y por cómo interactúan con vías de señalización.',
  offerCards: [
    { titleEn: 'Metabolic & Weight Optimization', titleEs: 'Metabolismo y peso', textEn: 'Research areas include metabolism, appetite regulation, and energy balance.', textEs: 'Áreas de investigación incluyen metabolismo, apetito y balance energético.' },
    { titleEn: 'Recovery & Tissue Support', titleEs: 'Recuperación y tejidos', textEn: 'Popular for research around tissue repair, joint support, and recovery routines.', textEs: 'Usados en investigación sobre reparación de tejidos, soporte articular y recuperación.' },
    { titleEn: 'Cognitive Performance & Mental Clarity', titleEs: 'Cognición y claridad mental', textEn: 'Studied for brain signaling, focus, and mental sharpness research.', textEs: 'Estudiados para señalización cerebral, enfoque y claridad mental.' },
    { titleEn: 'Skin & Regenerative Applications', titleEs: 'Piel y regeneración', textEn: 'Often researched for skin repair, collagen, and healthy tissue support.', textEs: 'Investigados para reparación de piel, colágeno y soporte de tejidos.' },
    { titleEn: 'Energy & Mitochondrial Function', titleEs: 'Energía y función mitocondrial', textEn: 'Explored for endurance, recovery, and cellular energy efficiency.', textEs: 'Explorados para resistencia, recuperación y eficiencia energética celular.' },
    { titleEn: 'Hormonal & Endocrine Signaling', titleEs: 'Señalización hormonal', textEn: 'Used in research focused on hormone signaling and endocrine balance.', textEs: 'Usados en investigación de señalización hormonal y balance endocrino.' },
  ],
  audienceTitleEn: 'Who This Is For',
  audienceTitleEs: 'Para quién es',
  audienceTextEn: 'Customers exploring performance, recovery, wellness, longevity, and research-backed product access in Costa Rica.',
  audienceTextEs: 'Clientes explorando rendimiento, recuperación, bienestar, longevidad y acceso local a productos de investigación.',
  audienceItems: [
    { titleEn: 'Performance-driven people', titleEs: 'Personas orientadas al rendimiento', textEn: 'Athletes, trainers, and active customers who want reliable local access.', textEs: 'Atletas, entrenadores y clientes activos que buscan acceso local confiable.' },
    { titleEn: 'Wellness and longevity enthusiasts', titleEs: 'Bienestar y longevidad', textEn: 'Customers researching recovery, energy, healthy aging, and resilience.', textEs: 'Clientes investigando recuperación, energía, envejecimiento saludable y resiliencia.' },
    { titleEn: 'Recovery-focused clients', titleEs: 'Clientes enfocados en recuperación', textEn: 'People comparing options for tissue, joint, and training recovery research.', textEs: 'Personas comparando opciones para investigación de tejido, articulaciones y recuperación.' },
    { titleEn: 'High-performance professionals', titleEs: 'Profesionales de alto rendimiento', textEn: 'Busy customers who need clear information and fast local coordination.', textEs: 'Clientes ocupados que necesitan información clara y coordinación local rápida.' },
  ],
  proofTitleEn: 'Real People. Real Results.',
  proofTitleEs: 'Personas reales. Resultados reales.',
  proofTextEn: 'Customer experiences vary, but clear ordering, direct support, and reliable local access make the process easier.',
  proofTextEs: 'Las experiencias varían, pero ordenar claro, soporte directo y acceso local confiable hacen el proceso más fácil.',
  proofImageUrl: '/customer_transformation.webp',
  qualityTitleEn: 'Trusted Quality.',
  qualityTitleEs: 'Calidad confiable.',
  qualityTextEn: 'Products are offered with transparent information, local availability, and customer-first support.',
  qualityTextEs: 'Productos con información transparente, disponibilidad local y soporte enfocado en el cliente.',
  faqTitleEn: 'Frequently Asked Questions',
  faqTitleEs: 'Preguntas frecuentes',
  faqItems: [
    { qEn: 'Do you ship outside Costa Rica?', qEs: '¿Envían fuera de Costa Rica?', aEn: 'No. We currently serve customers within Costa Rica only.', aEs: 'No. Actualmente servimos solo a clientes dentro de Costa Rica.' },
    { qEn: 'Do you offer online checkout?', qEs: '¿Tienen checkout en línea?', aEn: 'Yes. You can order through the catalog checkout or contact us directly on WhatsApp.', aEs: 'Sí. Puedes ordenar por el checkout del catálogo o contactarnos por WhatsApp.' },
    { qEn: 'What payment methods do you accept?', qEs: '¿Qué métodos de pago aceptan?', aEn: 'Available payment options are shown during checkout and confirmed by our team.', aEs: 'Las opciones de pago disponibles se muestran durante checkout y son confirmadas por nuestro equipo.' },
    { qEn: 'How quickly do you respond to inquiries?', qEs: '¿Qué tan rápido responden?', aEn: 'We aim to respond quickly during normal business hours, with WhatsApp as the fastest channel.', aEs: 'Intentamos responder rápido en horario laboral, con WhatsApp como canal principal.' },
  ],
  bulkTitleEn: 'Bulk Savings Program',
  bulkTitleEs: 'Programa de ahorro por volumen',
  bulkTextEn: 'Purchase five or more vials of the same product to receive 15% off.',
  bulkTextEs: 'Compra cinco o más viales del mismo producto y recibe 15% de descuento.',
  bulkButtonEn: 'Call To Order',
  bulkButtonEs: 'Llamar para ordenar',
  footerDescriptionEn: 'Peptides Costa Rica offers premium, research-backed peptides for weight loss, muscle growth, energy, recovery, and healthy aging with trusted quality and bulk savings across Costa Rica.',
  footerDescriptionEs: 'Peptides Costa Rica ofrece péptidos premium de investigación para peso, músculo, energía, recuperación y envejecimiento saludable con calidad confiable en Costa Rica.',
  legalNoticeEn: 'Products offered by Peptides Costa Rica are intended strictly for laboratory research use only. They are not approved or licensed by the FDA for the prevention, diagnosis, treatment, or cure of any disease. Information on this website is for educational purposes only and should not be considered medical or legal advice. Not for human or veterinary use.',
  legalNoticeEs: 'Los productos ofrecidos por Peptides Costa Rica son estrictamente para uso de investigación de laboratorio. No están aprobados para prevenir, diagnosticar, tratar o curar enfermedades. La información de este sitio es educativa y no constituye consejo médico o legal. No apto para uso humano o veterinario.',
  footerQuickLinks: [
    { labelEn: 'Home', labelEs: 'Inicio', href: '/' },
    { labelEn: 'About us', labelEs: 'Nosotros', href: '/our-story' },
    { labelEn: 'Bulk Discounts', labelEs: 'Descuentos por volumen', href: '/bulk-discounts' },
    { labelEn: 'FAQ', labelEs: 'Preguntas frecuentes', href: '/faq' },
    { labelEn: 'Blog', labelEs: 'Blog', href: '/blog' },
  ],
  footerCategoryLinks: [
    { labelEn: 'Peptides For Weight Loss', labelEs: 'Péptidos para pérdida de peso', href: '/catalog?category=Peptides%20For%20Weight%20Loss' },
    { labelEn: 'Peptides For Muscle Growth', labelEs: 'Péptidos para crecimiento muscular', href: '/catalog?category=Peptides%20For%20Muscle%20Growth' },
    { labelEn: 'Peptides For Anti Aging', labelEs: 'Péptidos anti-aging', href: '/catalog?category=Peptides%20For%20Anti%20Aging' },
    { labelEn: 'Peptides For Healing', labelEs: 'Péptidos para recuperación', href: '/catalog?category=Peptides%20For%20Healing' },
    { labelEn: 'View All', labelEs: 'Ver todo', href: '/catalog' },
  ],
};

export function mergeLandingPageSettings(value = {}) {
  if (value?.landingVersion !== 'v2') {
    return {
      ...DEFAULT_LANDING_PAGE_SETTINGS,
      bannerActive: value?.bannerActive ?? DEFAULT_LANDING_PAGE_SETTINGS.bannerActive,
      bannerTextEn: value?.bannerTextEn || DEFAULT_LANDING_PAGE_SETTINGS.bannerTextEn,
      bannerTextEs: value?.bannerTextEs || DEFAULT_LANDING_PAGE_SETTINGS.bannerTextEs,
    };
  }

  const merged = { ...DEFAULT_LANDING_PAGE_SETTINGS, ...(value || {}) };

  for (const key of ['differenceCards', 'offerCards', 'audienceItems', 'faqItems', 'heroDropdownOptions', 'footerQuickLinks', 'footerCategoryLinks']) {
    merged[key] = Array.isArray(value?.[key]) && value[key].length
      ? value[key]
      : DEFAULT_LANDING_PAGE_SETTINGS[key];
  }

  return merged;
}

export const PUBLIC_PAGE_SETTING_IDS = [
  'page_info_center',
  'page_our_story',
  'page_affiliate_program',
  'page_blog',
];

export const DEFAULT_PUBLIC_PAGE_SETTINGS = {
  page_info_center: {
    pageVersion: 'v1',
    heroKickerEn: 'Resource library',
    heroKickerEs: 'Biblioteca de recursos',
    heroTitleEn: 'The Peptide Info Center',
    heroTitleEs: 'Centro de información de péptidos',
    heroTextEn: 'Clear, simple answers about peptides, reconstitution, dosing questions, storage, and product comparisons.',
    heroTextEs: 'Respuestas claras sobre péptidos, reconstitución, preguntas de dosificación, almacenamiento y comparaciones.',
    searchPlaceholderEn: 'Search articles, peptides, or questions...',
    searchPlaceholderEs: 'Buscar artículos, péptidos o preguntas...',
    quickLinks: [
      { labelEn: 'How to reconstitute', labelEs: 'Cómo reconstituir', href: '/blog/how-to-reconstitute-peptides' },
      { labelEn: 'Dosing & injection guide', labelEs: 'Guía de dosificación', href: '/blog/dosing-injection-basics' },
      { labelEn: 'Storing peptides', labelEs: 'Almacenar péptidos', href: '/blog/storing-peptides-safely' },
      { labelEn: 'Retatrutide guide', labelEs: 'Guía de Retatrutide', href: '/blog/what-is-retatrutide' },
    ],
    startTitleEn: 'Start here',
    startTitleEs: 'Empieza aquí',
    steps: [
      { titleEn: 'How to reconstitute peptides', titleEs: 'Cómo reconstituir péptidos', textEn: 'Mix bacteriostatic water with your vial step by step.', textEs: 'Mezcla agua bacteriostática con tu vial paso a paso.' },
      { titleEn: 'Dosing & injection basics', titleEs: 'Bases de dosificación e inyección', textEn: 'How much to take, where to draw, and where to inject.', textEs: 'Cuánto tomar, dónde cargar y dónde aplicar.' },
      { titleEn: 'Storage & handling', titleEs: 'Almacenamiento y manejo', textEn: 'Keep products stable in Costa Rica climate.', textEs: 'Mantén productos estables en el clima de Costa Rica.' },
      { titleEn: 'Choosing your first peptide', titleEs: 'Elegir tu primer péptido', textEn: 'Match goals to the right compound.', textEs: 'Relaciona tus objetivos con el compuesto correcto.' },
    ],
    topics: [
      { titleEn: 'Foundations', titleEs: 'Fundamentos', textEn: 'The basics: what peptides are and how they work.', textEs: 'Lo básico: qué son los péptidos y cómo funcionan.' },
      { titleEn: 'Getting started', titleEs: 'Para empezar', textEn: 'Practical guides for buyers and new users.', textEs: 'Guías prácticas para compradores y usuarios nuevos.' },
      { titleEn: 'Healing & recovery', titleEs: 'Recuperación', textEn: 'BPC-157, TB-500, and tissue-repair peptides.', textEs: 'BPC-157, TB-500 y péptidos de reparación.' },
      { titleEn: 'Metabolic & weight', titleEs: 'Metabolismo y peso', textEn: 'Retatrutide, MOTS-C, and metabolic research.', textEs: 'Retatrutide, MOTS-C e investigación metabólica.' },
      { titleEn: 'Growth hormone & anti-aging', titleEs: 'GH y anti-aging', textEn: 'Sermorelin, CJC-1295, Tesamorelin, NAD+.', textEs: 'Sermorelin, CJC-1295, Tesamorelin, NAD+.' },
      { titleEn: 'Safety & side effects', titleEs: 'Seguridad y efectos', textEn: 'What research says about risk and tolerability.', textEs: 'Lo que dice la investigación sobre riesgos y tolerancia.' },
    ],
    coaTitleEn: 'COA Library',
    coaTitleEs: 'Biblioteca COA',
    coaTextEn: 'Placeholder COA links are ready for your real PDF or lab report URLs.',
    coaTextEs: 'Enlaces COA de ejemplo listos para reemplazar por PDFs o reportes reales.',
    coaLinks: [
      { labelEn: 'BPC-157 COA', labelEs: 'COA BPC-157', href: '/catalog' },
      { labelEn: 'Retatrutide COA', labelEs: 'COA Retatrutide', href: '/catalog' },
      { labelEn: 'GHK-Cu COA', labelEs: 'COA GHK-Cu', href: '/catalog' },
    ],
    ctaTitleEn: "Can't find what you're looking for?",
    ctaTitleEs: '¿No encuentras lo que buscas?',
    ctaTextEn: 'Our team is happy to help with product or dosing questions over a call.',
    ctaTextEs: 'Nuestro equipo puede ayudar con preguntas de productos o dosificación.',
  },
  page_our_story: {
    pageVersion: 'v1',
    heroTitleEn: 'Our Story',
    heroTitleEs: 'Nuestra historia',
    heroTextEn: 'Peptides Costa Rica was built by people who live, train, and work in Costa Rica.',
    heroTextEs: 'Peptides Costa Rica fue creado por personas que viven, entrenan y trabajan en Costa Rica.',
    sections: [
      { titleEn: 'From the Fight World to Peptides Costa Rica', titleEs: 'Del mundo del combate a Peptides Costa Rica', textEn: 'Our business began not in an office, but in gyms, fight camps, and recovery rooms.', textEs: 'Nuestro negocio comenzó no en una oficina, sino en gimnasios, campamentos y recuperación.', imageUrl: '/vials_group_costarica.png' },
      { titleEn: 'Sean McCully: A Pioneer in Combat Sports', titleEs: 'Sean McCully: pionero en deportes de combate', textEn: 'Sean spent decades competing, coaching, and building businesses in the fight world.', textEs: 'Sean pasó décadas compitiendo, entrenando y creando negocios en el mundo del combate.', imageUrl: '/customer_transformation.webp' },
      { titleEn: 'Joey Webster: From Wrestling Champion to Fighter', titleEs: 'Joey Webster: de campeón de lucha a peleador', textEn: 'Joey grew up wrestling in California and made Costa Rica his home.', textEs: 'Joey creció en la lucha en California e hizo de Costa Rica su hogar.', imageUrl: '/modern_3d_vials_group.png' },
      { titleEn: 'Why We Started Peptides Costa Rica', titleEs: 'Por qué empezamos Peptides Costa Rica', textEn: 'We wanted clear pricing, local availability, direct communication, and confirmed product access.', textEs: 'Queríamos precios claros, disponibilidad local, comunicación directa y acceso confirmado.', imageUrl: '/vial_costarica_hero.png' },
    ],
    checklist: [
      { labelEn: 'Clear sourcing', labelEs: 'Origen claro' },
      { labelEn: 'Direct communication', labelEs: 'Comunicación directa' },
      { labelEn: 'Fewer delays', labelEs: 'Menos demoras' },
      { labelEn: 'Confirmed availability', labelEs: 'Disponibilidad confirmada' },
    ],
    toolsImageUrl: '/science_lab_about.webp',
    toolsTitleEn: 'The Tools We Use Ourselves',
    toolsTitleEs: 'Las herramientas que usamos nosotros',
    toolsTextEn: 'Everything we offer comes from the world we know best: training, recovery, and performance. We focus on clear communication, reliable access, and honest information.',
    toolsTextEs: 'Todo lo que ofrecemos viene del mundo que conocemos mejor: entrenamiento, recuperación y rendimiento. Nos enfocamos en comunicación clara, acceso confiable e información honesta.',
    ctaTitleEn: 'Browse all peptide products',
    ctaTitleEs: 'Explora todos los productos',
    ctaTextEn: 'See current local availability in the catalog.',
    ctaTextEs: 'Mira la disponibilidad local actual en el catálogo.',
  },
  page_affiliate_program: {
    pageVersion: 'v1',
    heroKickerEn: 'Partner with us',
    heroKickerEs: 'Colabora con nosotros',
    heroTitleEn: 'Earn by recommending the peptides you already trust',
    heroTitleEs: 'Gana recomendando los péptidos que ya recomiendas',
    heroTextEn: 'Our affiliate program is built for professionals and customer advocates who want a clear local supply partner.',
    heroTextEs: 'Nuestro programa de afiliados es para profesionales y referentes que quieren un proveedor local claro.',
    heroImageUrl: '/science_lab_about.webp',
    primaryButtonEn: 'Apply to Partner',
    primaryButtonEs: 'Aplicar',
    secondaryButtonEn: 'Chat on WhatsApp',
    secondaryButtonEs: 'Chatear por WhatsApp',
    audienceTitleEn: 'Who This Program Is For',
    audienceTitleEs: 'Para quién es este programa',
    audienceCards: [
      { titleEn: 'Health Clinics', titleEs: 'Clínicas', textEn: 'Wellness, integrative, longevity, and recovery clinics.', textEs: 'Clínicas de bienestar, longevidad y recuperación.' },
      { titleEn: 'Doctors & Practitioners', titleEs: 'Doctores y profesionales', textEn: 'Physicians and providers who need trusted local products.', textEs: 'Profesionales que necesitan productos locales confiables.' },
      { titleEn: 'Gyms & Trainers', titleEs: 'Gimnasios y entrenadores', textEn: 'Performance coaches and recovery specialists.', textEs: 'Coaches de rendimiento y especialistas en recuperación.' },
      { titleEn: 'Health Influencers', titleEs: 'Influencers de salud', textEn: 'Creators who educate customers responsibly.', textEs: 'Creadores que educan clientes de forma responsable.' },
    ],
    benefitsTitleEn: 'What You Get as a Partner',
    benefitsTitleEs: 'Qué recibes como partner',
    benefits: [
      { titleEn: 'Competitive commissions', titleEs: 'Comisiones competitivas', textEn: 'Earn for qualified referrals and repeat orders.', textEs: 'Gana por referidos calificados y órdenes repetidas.' },
      { titleEn: 'Reliable local supply', titleEs: 'Suministro local confiable', textEn: 'Products are already coordinated in Costa Rica.', textEs: 'Productos coordinados localmente en Costa Rica.' },
      { titleEn: 'Educational resources', titleEs: 'Recursos educativos', textEn: 'Support materials help customers make informed decisions.', textEs: 'Materiales de soporte para decisiones informadas.' },
      { titleEn: 'Personalized promo codes', titleEs: 'Códigos personalizados', textEn: 'Give your audience a clear way to order.', textEs: 'Da a tu audiencia una forma clara de ordenar.' },
    ],
    faqTitleEn: 'Common Questions',
    faqTitleEs: 'Preguntas comunes',
    faqItems: [
      { qEn: 'Do I need to stock products myself?', qEs: '¿Debo tener inventario?', aEn: 'No. Refer customers to us directly and we coordinate locally.', aEs: 'No. Refiere clientes y nosotros coordinamos localmente.' },
      { qEn: 'How are commissions paid?', qEs: '¿Cómo se pagan comisiones?', aEn: 'We agree on the structure before launch and track qualified referrals.', aEs: 'Acordamos la estructura antes de iniciar y damos seguimiento a referidos.' },
      { qEn: 'Is there a minimum commitment?', qEs: '¿Hay compromiso mínimo?', aEn: 'No. The program can scale with your audience or client base.', aEs: 'No. El programa puede crecer con tu audiencia o clientes.' },
    ],
    talkTitleEn: "Let's Talk",
    talkTitleEs: 'Hablemos',
    talkTextEn: 'Reach out by WhatsApp to start the conversation.',
    talkTextEs: 'Escríbenos por WhatsApp para iniciar la conversación.',
  },
  page_blog: {
    pageVersion: 'v1',
    heroKickerEn: 'Info center',
    heroKickerEs: 'Centro de información',
    heroTitleEn: 'Peptide research, explained clearly.',
    heroTitleEs: 'Investigación de péptidos, explicada claramente.',
    heroTextEn: 'Evidence-minded articles, practical guides, and company updates from Peptides Costa Rica.',
    heroTextEs: 'Artículos basados en evidencia, guías prácticas y novedades de Peptides Costa Rica.',
    articleCtaTitleEn: 'Research-grade products, available locally.',
    articleCtaTitleEs: 'Productos de investigación, disponibles localmente.',
    articleCtaTextEn: 'Browse transparent product information and current availability in our Costa Rica catalog.',
    articleCtaTextEs: 'Consulta información transparente y disponibilidad actual en nuestro catálogo de Costa Rica.',
    articleCtaButtonEn: 'View products',
    articleCtaButtonEs: 'Ver productos',
    fallbackPosts: [
      {
        id: 'fallback-1',
        slug: 'how-to-reconstitute-peptides',
        title_en: 'How to reconstitute peptides',
        title_es: 'Cómo reconstituir péptidos',
        excerpt_en: 'A simple starter guide for mixing bacteriostatic water with peptide vials.',
        excerpt_es: 'Una guía simple para mezclar agua bacteriostática con viales de péptidos.',
        content_en: 'This placeholder article is ready to replace from the dashboard. Add your full reconstitution guide here, including product-specific cautions, storage notes, and support instructions.',
        content_es: 'Este artículo de ejemplo está listo para reemplazarse desde el dashboard. Agrega aquí tu guía completa de reconstitución, incluyendo precauciones por producto, almacenamiento e instrucciones de soporte.',
        image_url: '/catalog-promo-banner.webp',
        created_at: '2026-07-20T12:00:00.000Z',
      },
      {
        id: 'fallback-2',
        slug: 'peptide-delivery-costa-rica',
        title_en: 'Peptide delivery in Costa Rica',
        title_es: 'Entrega de péptidos en Costa Rica',
        excerpt_en: 'Availability, payment, and ordering basics for local customers.',
        excerpt_es: 'Disponibilidad, pago y conceptos básicos para clientes locales.',
        content_en: 'Use this placeholder to explain delivery areas, payment confirmation, and how customers can coordinate orders through the catalog or WhatsApp.',
        content_es: 'Usa este espacio para explicar zonas de entrega, confirmación de pago y cómo los clientes pueden coordinar pedidos desde el catálogo o WhatsApp.',
        image_url: '/vials_group_costarica.png',
        created_at: '2026-07-18T12:00:00.000Z',
      },
      {
        id: 'fallback-3',
        slug: 'what-is-retatrutide',
        title_en: 'What is Retatrutide?',
        title_es: '¿Qué es Retatrutide?',
        excerpt_en: 'A plain-language overview of one of the most requested research compounds.',
        excerpt_es: 'Un resumen claro de uno de los compuestos de investigación más solicitados.',
        content_en: 'Replace this placeholder with a careful educational article, including research context, common questions, and links to product availability or COA documents.',
        content_es: 'Reemplaza este ejemplo con un artículo educativo cuidadoso, incluyendo contexto de investigación, preguntas comunes y enlaces a disponibilidad o documentos COA.',
        image_url: '/hero_peptide_vial.png',
        created_at: '2026-07-17T12:00:00.000Z',
      },
    ],
  },
};

export function mergePublicPageSettings(pageId, value = {}) {
  const defaults = DEFAULT_PUBLIC_PAGE_SETTINGS[pageId] || {};
  if (value?.pageVersion !== defaults.pageVersion) return defaults;
  const merged = { ...defaults, ...(value || {}) };
  for (const key of ['quickLinks', 'steps', 'topics', 'coaLinks', 'sections', 'checklist', 'audienceCards', 'benefits', 'faqItems', 'fallbackPosts']) {
    merged[key] = Array.isArray(value?.[key]) && value[key].length ? value[key] : defaults[key];
  }
  return merged;
}

export function mergeAllPublicPageSettings(records = {}) {
  return Object.fromEntries(
    PUBLIC_PAGE_SETTING_IDS.map((id) => [id, mergePublicPageSettings(id, records[id])])
  );
}
