{activeTab === 'carts' && (
          <div className="admin-orders-tab admin-tab-panel">
            <div className="admin-section-header">
              <h2 className="admin-section-title">🛒 Active / Abandoned Carts</h2>
              <div className="admin-toolbar-actions">
                {abandonedCarts.length > 0 && (
                  <>
                    <button
                      onClick={() => setExportModalType('carts')}
                      style={{ padding: '6px 14px', fontSize: '0.85rem', background: 'rgba(56, 189, 248, 0.1)', border: '1px solid rgba(56, 189, 248, 0.2)', color: '#38bdf8', borderRadius: '8px', cursor: 'pointer', fontWeight: '700', display: 'flex', alignItems: 'center', gap: '5px' }}
                    >
                      <Upload size={13} /> Export Data
                    </button>
                    <button
                      onClick={handleClearAllCarts}
                      style={{ padding: '6px 14px', fontSize: '0.85rem', background: 'rgba(239, 68, 68, 0.12)', border: '1px solid rgba(239, 68, 68, 0.3)', color: '#f87171', borderRadius: '8px', cursor: 'pointer', fontWeight: '700', display: 'flex', alignItems: 'center', gap: '5px' }}
                    >
                      <Trash2 size={13} /> Clear All
                    </button>
                  </>
                )}
                <button className="admin-btn" onClick={loadAdminData} style={{ padding: '6px 14px', fontSize: '0.85rem', background: 'rgba(56, 189, 248, 0.1)', border: '1px solid rgba(56, 189, 248, 0.2)', color: '#38bdf8', borderRadius: '8px', cursor: 'pointer', fontWeight: '700' }}>
                  Refresh
                </button>
              </div>
            </div>

            {/* CARTS AI RECOVERY INSIGHTS CARD */}
            <div style={{ marginBottom: '24px' }}>
              {generatingCartsAi ? (
                <div style={{ background: 'linear-gradient(135deg, rgba(14, 22, 38, 0.9) 0%, rgba(30, 41, 59, 0.9) 100%)', border: '1px solid rgba(56, 189, 248, 0.2)', borderRadius: '16px', padding: '24px', position: 'relative', overflow: 'hidden', boxShadow: '0 8px 32px 0 rgba(0, 0, 0, 0.37)' }}>
                  <div style={{ display: 'flex', alignItems: 'center', gap: '16px' }}>
                    <div className="sync-spinner" style={{ color: '#38bdf8' }}><Brain size={32} /></div>
                    <div>
                      <h4 style={{ fontSize: '1rem', fontWeight: 'bold', color: '#f8fafc', margin: '0 0 4px 0' }}>🧬 AI Copilot is auditing active abandoned carts and pipeline...</h4>
                      <p style={{ fontSize: '0.8rem', color: '#94a3b8', margin: 0 }}>Compiling peptide cart values, measuring checkout leakage frequency, and drafting recovery discount hooks...</p>
                    </div>
                  </div>
                </div>
              ) : cartsAiText ? (
                <div style={{ background: 'linear-gradient(135deg, rgba(14, 26, 51, 0.9) 0%, rgba(15, 23, 42, 0.9) 100%)', border: '1px solid rgba(56, 189, 248, 0.3)', borderRadius: '16px', padding: '24px', boxShadow: '0 10px 40px -10px rgba(56, 189, 248, 0.15)', position: 'relative' }}>
                  <button 
                    onClick={() => setCartsAiText('')}
                    style={{ position: 'absolute', top: '16px', right: '16px', background: 'rgba(255,255,255,0.05)', border: 'none', color: '#94a3b8', borderRadius: '50%', width: '28px', height: '28px', cursor: 'pointer', display: 'flex', alignItems: 'center', justifyContent: 'center' }}
                  >
                    &times;
                  </button>
                  <div style={{ display: 'flex', alignItems: 'center', gap: '10px', marginBottom: '16px', borderBottom: '1px solid rgba(255,255,255,0.06)', paddingBottom: '12px' }}>
                    <div style={{ background: 'rgba(56, 189, 248, 0.1)', padding: '8px', borderRadius: '10px', color: '#38bdf8' }}>
                      <Sparkles size={20} />
                    </div>
                    <div>
                      <h4 style={{ fontSize: '1.05rem', fontWeight: 'bold', color: '#f8fafc', margin: 0 }}>🧬 Real-Time AI Cart Recovery Strategy</h4>
                      <span style={{ fontSize: '0.75rem', color: '#64748b' }}>Generated by Gemini • Data-Driven Recovery hooks</span>
                    </div>
                  </div>
                  
                  <div 
                    style={{ fontSize: '0.85rem', color: '#cbd5e1', lineHeight: '1.6', whiteSpace: 'pre-wrap' }}
                    dangerouslySetInnerHTML={{
                      __html: cartsAiText
                        .replace(/\*\*(.*?)\*\*/g, '<strong style="color: #38bdf8">$1</strong>')
                        .replace(/^- (.*)$/gm, '<li style="margin-left: 12px; margin-bottom: 6px; list-style-type: square">$1</li>')
                    }}
                  />
                </div>
              ) : (
                <div 
                  onClick={handleGenerateCartsAi}
                  className="admin-ai-insight-card"
                  style={{ background: 'linear-gradient(135deg, rgba(30, 41, 59, 0.25) 0%, rgba(15, 23, 42, 0.45) 100%)', border: '1px solid rgba(255,255,255,0.05)', borderRadius: '16px', padding: '16px 20px', cursor: 'pointer', display: 'flex', alignItems: 'center', justifyContent: 'space-between', transition: 'all 0.2s', boxShadow: '0 4px 20px rgba(0, 0, 0, 0.1)' }}
                >
                  <div style={{ display: 'flex', alignItems: 'center', gap: '12px' }}>
                    <div style={{ background: 'rgba(56, 189, 248, 0.1)', padding: '10px', borderRadius: '12px', color: '#38bdf8' }}>
                      <Brain size={20} />
                    </div>
                    <div>
                      <h4 style={{ fontSize: '0.9rem', fontWeight: 'bold', color: '#f8fafc', margin: '0 0 2px 0' }}>✨ Generate Real-Time AI Cart Recovery Insights</h4>
                      <p style={{ fontSize: '0.75rem', color: '#94a3b8', margin: 0 }}>Analyze abandoned carts list, map product abandonment frequency, and draft high-converting Spanish WhatsApp pitches.</p>
                    </div>
                  </div>
                  <button 
                    className="admin-btn admin-btn-primary" 
                    style={{ padding: '8px 16px', display: 'flex', alignItems: 'center', gap: '6px', borderRadius: '8px', fontSize: '0.8rem', cursor: 'pointer' }}
                    onClick={(e) => {
                      e.stopPropagation();
                      handleGenerateCartsAi();
                    }}
                  >
                    <Sparkles size={13} /> Audit Carts
                  </button>
                </div>
              )}
            </div>

            {/* BULK PROCESSING PROGRESS INDICATOR OVERLAY */}
            {bulkProcessing && (
              <div style={{
                background: 'linear-gradient(135deg, rgba(14, 22, 38, 0.9) 0%, rgba(30, 41, 59, 0.9) 100%)',
                border: '1px solid rgba(56, 189, 248, 0.3)',
                borderRadius: '16px',
                padding: '24px',
                marginBottom: '20px',
                boxShadow: '0 8px 32px 0 rgba(0, 0, 0, 0.5)',
                display: 'flex',
                alignItems: 'center',
                gap: '16px'
              }}>
                <div className="sync-spinner" style={{ color: '#38bdf8' }}><Brain size={32} /></div>
                <div>
                  <h4 style={{ fontSize: '1rem', fontWeight: 'bold', color: '#f8fafc', margin: '0 0 4px 0' }}>⚡ Processing Bulk Operation...</h4>
                  <p style={{ fontSize: '0.85rem', color: '#38bdf8', margin: 0, fontWeight: 'bold' }}>{bulkProgressText}</p>
                </div>
              </div>
            )}

            {selectedCartIds.length > 0 && !bulkProcessing && (
              <div style={{ 
                background: 'linear-gradient(90deg, rgba(56, 189, 248, 0.12) 0%, rgba(168, 85, 247, 0.12) 100%)', 
                border: '1px solid rgba(56, 189, 248, 0.3)', 
                borderRadius: '12px', 
                padding: '16px 20px', 
                marginBottom: '20px', 
                display: 'flex', 
                justifyContent: 'space-between', 
                alignItems: 'center',
                flexWrap: 'wrap',
                gap: '12px',
                boxShadow: '0 4px 20px rgba(0, 0, 0, 0.15)'
              }}>
                <span style={{ fontSize: '0.85rem', color: '#cbd5e1', fontWeight: 'bold' }}>
                  ⚡ Selected <span style={{ color: '#38bdf8', fontSize: '1rem' }}>{selectedCartIds.length}</span> {selectedCartIds.length === 1 ? 'cart' : 'carts'} for bulk actions
                </span>
                <div style={{ display: 'flex', gap: '8px' }}>
                  <button 
                    onClick={handleBulkEmail}
                    className="admin-btn"
                    style={{ background: 'rgba(56, 189, 248, 0.25)', border: '1px solid rgba(56, 189, 248, 0.4)', color: '#38bdf8', padding: '8px 16px', fontSize: '0.8rem', fontWeight: 'bold', cursor: 'pointer', borderRadius: '8px' }}
                  >
                    ✉️ Bulk Email Reminder
                  </button>
                  <button 
                    onClick={handleBulkWhatsApp}
                    className="admin-btn"
                    style={{ background: 'rgba(34, 197, 94, 0.25)', border: '1px solid rgba(34, 197, 94, 0.4)', color: '#4ade80', padding: '8px 16px', fontSize: '0.8rem', fontWeight: 'bold', cursor: 'pointer', borderRadius: '8px' }}
                  >
                    💬 Bulk WhatsApp Reminder
                  </button>
                  <button 
                    onClick={handleBulkDelete}
                    className="admin-btn"
                    style={{ background: 'rgba(239, 68, 68, 0.25)', border: '1px solid rgba(239, 68, 68, 0.4)', color: '#f87171', padding: '8px 16px', fontSize: '0.8rem', fontWeight: 'bold', cursor: 'pointer', borderRadius: '8px' }}
                  >
                    🗑️ Bulk Delete Carts
                  </button>
                </div>
              </div>
            )}

            {/* MINI REVENUE DASHBOARD & FILTERS */}
            {abandonedCarts.length > 0 && (() => {
              const totalAbandonedValue = abandonedCarts.reduce((sum, c) => sum + getCartValue(c), 0);
              const recoveredCarts = abandonedCarts.filter(c => getCartRecoveryStatus(c) === 'recovered');
              const totalRecoveredValue = recoveredCarts.reduce((sum, c) => sum + getCartValue(c), 0);
              const recoveryRate = abandonedCarts.length > 0 ? ((recoveredCarts.length / abandonedCarts.length) * 100).toFixed(1) : '0.0';

              return (
                <div style={{ marginBottom: '24px', display: 'flex', flexDirection: 'column', gap: '16px' }}>
                  
                  {/* Dashboard Cards */}
                  <div style={{ 
                    display: 'grid', 
                    gridTemplateColumns: 'repeat(auto-fit, minmax(200px, 1fr))', 
                    gap: '16px' 
                  }}>
                    <div style={{ background: 'linear-gradient(145deg, #0f172a, #1e293b)', border: '1px solid rgba(255,255,255,0.05)', borderRadius: '16px', padding: '20px', boxShadow: '0 4px 12px rgba(0,0,0,0.2)' }}>
                      <div style={{ fontSize: '0.8rem', color: '#94a3b8', textTransform: 'uppercase', letterSpacing: '0.05em', marginBottom: '8px', display: 'flex', alignItems: 'center', gap: '6px' }}>
                        <span style={{ color: '#f87171' }}>📉</span> Lost Revenue
                      </div>
                      <div style={{ fontSize: '1.75rem', fontWeight: '800', color: '#f8fafc' }}>
                        ${totalAbandonedValue.toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 })}
                      </div>
                    </div>
                    
                    <div style={{ background: 'linear-gradient(145deg, #0f172a, #1e293b)', border: '1px solid rgba(255,255,255,0.05)', borderRadius: '16px', padding: '20px', boxShadow: '0 4px 12px rgba(0,0,0,0.2)' }}>
                      <div style={{ fontSize: '0.8rem', color: '#94a3b8', textTransform: 'uppercase', letterSpacing: '0.05em', marginBottom: '8px', display: 'flex', alignItems: 'center', gap: '6px' }}>
                        <span style={{ color: '#4ade80' }}>📈</span> Recovered Revenue
                      </div>
                      <div style={{ fontSize: '1.75rem', fontWeight: '800', color: '#f8fafc' }}>
                        ${totalRecoveredValue.toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 })}
                      </div>
                    </div>
                    
                    <div style={{ background: 'linear-gradient(145deg, #0f172a, #1e293b)', border: '1px solid rgba(255,255,255,0.05)', borderRadius: '16px', padding: '20px', boxShadow: '0 4px 12px rgba(0,0,0,0.2)' }}>
                      <div style={{ fontSize: '0.8rem', color: '#94a3b8', textTransform: 'uppercase', letterSpacing: '0.05em', marginBottom: '8px', display: 'flex', alignItems: 'center', gap: '6px' }}>
                        <span style={{ color: '#38bdf8' }}>⚡</span> Recovery Rate
                      </div>
                      <div style={{ fontSize: '1.75rem', fontWeight: '800', color: '#f8fafc' }}>
                        {recoveryRate}% <span style={{ fontSize: '0.9rem', color: '#94a3b8', fontWeight: 'normal' }}>({recoveredCarts.length} saved)</span>
                      </div>
                    </div>
                  </div>

                  {/* Filters Bar */}
                  <div style={{ 
                    background: '#0e1626', 
                    border: '1px solid rgba(255,255,255,0.1)', 
                    borderRadius: '16px', 
                    padding: '16px',
                    display: 'flex',
                    flexDirection: 'column',
                    gap: '16px',
                    boxShadow: '0 4px 12px rgba(0,0,0,0.15)'
                  }}>
                    <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', flexWrap: 'wrap', gap: '12px' }}>
                      <span style={{ fontSize: '1rem', color: '#e2e8f0', fontWeight: 'bold', display: 'flex', alignItems: 'center', gap: '8px' }}>
                        🔍 Advanced Filters
                      </span>
                      
                      <button 
                        onClick={() => {
                          const exportData = abandonedCarts.filter(c => {
                            let matchContact = true;
                            if (cartFilterContact === 'has_email') matchContact = !!c.customer_email;
                            if (cartFilterContact === 'has_phone') matchContact = !!c.customer_phone;
                            if (cartFilterContact === 'actionable') matchContact = !!c.customer_email || !!c.customer_phone;
                            if (cartFilterContact === 'none') matchContact = !c.customer_email && !c.customer_phone;
                            
                            let matchStatus = true;
                            if (cartFilterStatus === 'not_contacted') matchStatus = !getCartRecoveryStatus(c) || getCartRecoveryStatus(c) === 'not_contacted';
                            if (cartFilterStatus === 'contacted') matchStatus = getCartRecoveryStatus(c) === 'contacted_email' || getCartRecoveryStatus(c) === 'contacted_whatsapp';
                            if (cartFilterStatus === 'recovered') matchStatus = getCartRecoveryStatus(c) === 'recovered';
                            
                            let matchValue = true;
                            const val = getCartValue(c);
                            if (cartFilterValue === 'high') matchValue = val >= 100;
                            if (cartFilterValue === 'low') matchValue = val < 100;
                            
                            return matchContact && matchStatus && matchValue;
                          });
                          handleExportCartsCSV(exportData);
                        }}
                        style={{ 
                          padding: '8px 16px', 
                          background: 'linear-gradient(90deg, #38bdf8 0%, #2563eb 100%)', 
                          border: 'none', 
                          color: '#ffffff', 
                          borderRadius: '8px', 
                          fontSize: '0.85rem', 
                          fontWeight: 'bold',
                          cursor: 'pointer',
                          display: 'flex',
                          alignItems: 'center',
                          gap: '6px',
                          boxShadow: '0 2px 8px rgba(56, 189, 248, 0.4)',
                          transition: 'transform 0.2s'
                        }}
                        onMouseOver={(e) => e.currentTarget.style.transform = 'scale(1.02)'}
                        onMouseOut={(e) => e.currentTarget.style.transform = 'scale(1)'}
                      >
                        📥 Export Filtered CSV
                      </button>
                    </div>

                    <div style={{ 
                      display: 'grid',
                      gridTemplateColumns: 'repeat(auto-fit, minmax(180px, 1fr))',
                      gap: '16px'
                    }}>
                      <div style={{ display: 'flex', flexDirection: 'column', gap: '6px' }}>
                        <label style={{ fontSize: '0.75rem', color: '#94a3b8', fontWeight: 'bold', letterSpacing: '0.05em' }}>CONTACT INFO</label>
                        <select 
                          value={cartFilterContact} 
                          onChange={(e) => setCartFilterContact(e.target.value)} 
                          style={{ 
                            padding: '12px 14px', 
                            borderRadius: '10px', 
                            background: 'rgba(255,255,255,0.03)', 
                            border: '1px solid rgba(255,255,255,0.1)', 
                            color: '#f8fafc', 
                            fontSize: '0.9rem',
                            outline: 'none',
                            cursor: 'pointer',
                            appearance: 'none',
                            backgroundImage: 'url("data:image/svg+xml;charset=US-ASCII,%3Csvg%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20width%3D%22292.4%22%20height%3D%22292.4%22%3E%3Cpath%20fill%3D%22%2394a3b8%22%20d%3D%22M287%2069.4a17.6%2017.6%200%200%200-13-5.4H18.4c-5%200-9.3%201.8-12.9%205.4A17.6%2017.6%200%200%200%200%2082.2c0%205%201.8%209.3%205.4%2012.9l128%20127.9c3.6%203.6%207.8%205.4%2012.8%205.4s9.2-1.8%2012.8-5.4L287%2095c3.5-3.5%205.4-7.8%205.4-12.8%200-5-1.9-9.2-5.5-12.8z%22%2F%3E%3C%2Fsvg%3E")',
                            backgroundRepeat: 'no-repeat',
                            backgroundPosition: 'right 14px top 50%',
                            backgroundSize: '10px auto',
                            transition: 'border-color 0.2s'
                          }}
                          onFocus={(e) => e.target.style.borderColor = '#38bdf8'}
                          onBlur={(e) => e.target.style.borderColor = 'rgba(255,255,255,0.1)'}
                        >
                          <option value="all" style={{ background: '#0f172a' }}>All Contacts</option>
                          <option value="has_email" style={{ background: '#0f172a' }}>Has Email Address</option>
                          <option value="has_phone" style={{ background: '#0f172a' }}>Has Phone Number</option>
                          <option value="actionable" style={{ background: '#0f172a' }}>Actionable (Email or Phone)</option>
                          <option value="none" style={{ background: '#0f172a' }}>No Contact Info</option>
                        </select>
                      </div>

                      <div style={{ display: 'flex', flexDirection: 'column', gap: '6px' }}>
                        <label style={{ fontSize: '0.75rem', color: '#94a3b8', fontWeight: 'bold', letterSpacing: '0.05em' }}>RECOVERY STATUS</label>
                        <select 
                          value={cartFilterStatus} 
                          onChange={(e) => setCartFilterStatus(e.target.value)} 
                          style={{ 
                            padding: '12px 14px', 
                            borderRadius: '10px', 
                            background: 'rgba(255,255,255,0.03)', 
                            border: '1px solid rgba(255,255,255,0.1)', 
                            color: '#f8fafc', 
                            fontSize: '0.9rem',
                            outline: 'none',
                            cursor: 'pointer',
                            appearance: 'none',
                            backgroundImage: 'url("data:image/svg+xml;charset=US-ASCII,%3Csvg%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20width%3D%22292.4%22%20height%3D%22292.4%22%3E%3Cpath%20fill%3D%22%2394a3b8%22%20d%3D%22M287%2069.4a17.6%2017.6%200%200%200-13-5.4H18.4c-5%200-9.3%201.8-12.9%205.4A17.6%2017.6%200%200%200%200%2082.2c0%205%201.8%209.3%205.4%2012.9l128%20127.9c3.6%203.6%207.8%205.4%2012.8%205.4s9.2-1.8%2012.8-5.4L287%2095c3.5-3.5%205.4-7.8%205.4-12.8%200-5-1.9-9.2-5.5-12.8z%22%2F%3E%3C%2Fsvg%3E")',
                            backgroundRepeat: 'no-repeat',
                            backgroundPosition: 'right 14px top 50%',
                            backgroundSize: '10px auto',
                            transition: 'border-color 0.2s'
                          }}
                          onFocus={(e) => e.target.style.borderColor = '#38bdf8'}
                          onBlur={(e) => e.target.style.borderColor = 'rgba(255,255,255,0.1)'}
                        >
                          <option value="all" style={{ background: '#0f172a' }}>All Statuses</option>
                          <option value="not_contacted" style={{ background: '#0f172a' }}>Pending (Not Contacted)</option>
                          <option value="contacted" style={{ background: '#0f172a' }}>Contacted</option>
                          <option value="recovered" style={{ background: '#0f172a' }}>Recovered</option>
                        </select>
                      </div>

                      <div style={{ display: 'flex', flexDirection: 'column', gap: '6px' }}>
                        <label style={{ fontSize: '0.75rem', color: '#94a3b8', fontWeight: 'bold', letterSpacing: '0.05em' }}>CART VALUE</label>
                        <select 
                          value={cartFilterValue} 
                          onChange={(e) => setCartFilterValue(e.target.value)} 
                          style={{ 
                            padding: '12px 14px', 
                            borderRadius: '10px', 
                            background: 'rgba(255,255,255,0.03)', 
                            border: '1px solid rgba(255,255,255,0.1)', 
                            color: '#f8fafc', 
                            fontSize: '0.9rem',
                            outline: 'none',
                            cursor: 'pointer',
                            appearance: 'none',
                            backgroundImage: 'url("data:image/svg+xml;charset=US-ASCII,%3Csvg%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20width%3D%22292.4%22%20height%3D%22292.4%22%3E%3Cpath%20fill%3D%22%2394a3b8%22%20d%3D%22M287%2069.4a17.6%2017.6%200%200%200-13-5.4H18.4c-5%200-9.3%201.8-12.9%205.4A17.6%2017.6%200%200%200%200%2082.2c0%205%201.8%209.3%205.4%2012.9l128%20127.9c3.6%203.6%207.8%205.4%2012.8%205.4s9.2-1.8%2012.8-5.4L287%2095c3.5-3.5%205.4-7.8%205.4-12.8%200-5-1.9-9.2-5.5-12.8z%22%2F%3E%3C%2Fsvg%3E")',
                            backgroundRepeat: 'no-repeat',
                            backgroundPosition: 'right 14px top 50%',
                            backgroundSize: '10px auto',
                            transition: 'border-color 0.2s'
                          }}
                          onFocus={(e) => e.target.style.borderColor = '#38bdf8'}
                          onBlur={(e) => e.target.style.borderColor = 'rgba(255,255,255,0.1)'}
                        >
                          <option value="all" style={{ background: '#0f172a' }}>All Values</option>
                          <option value="high" style={{ background: '#0f172a' }}>High Value (&gt;$100)</option>
                          <option value="low" style={{ background: '#0f172a' }}>Low Value (&lt;$100)</option>
                        </select>
                      </div>
                    </div>
                  </div>
                </div>
              );
            })()}

            {loadingAbandonedCarts ? (
              <div style={{ textAlign: 'center', padding: '40px', color: '#94a3b8' }}>Loading carts...</div>
            ) : abandonedCarts.length === 0 ? (
              <div style={{ textAlign: 'center', padding: '40px', background: '#0e1626', borderRadius: '12px', border: '1px solid rgba(255,255,255,0.05)', color: '#94a3b8' }}>
                No active or abandoned carts currently.
              </div>
            ) : (
              <div className="table-responsive" style={{ background: '#0e1626', borderRadius: '12px', overflowX: 'auto', border: '1px solid rgba(255,255,255,0.05)' }}>
                <table className="spreadsheet-table responsive-table">
                  <thead>
                    <tr>
                      <th style={{ padding: '10px 12px', width: '40px', textAlign: 'center' }}>
                        <input 
                          type="checkbox" 
                          checked={selectedCartIds.length === abandonedCarts.length && abandonedCarts.length > 0} 
                          onChange={(e) => {
                            if (e.target.checked) {
                              setSelectedCartIds(abandonedCarts.map(c => c.session_id));
                            } else {
                              setSelectedCartIds([]);
                            }
                          }}
                          style={{ cursor: 'pointer', transform: 'scale(1.1)' }}
                        />
                      </th>
                      <th style={{ padding: '10px 12px', cursor: 'pointer' }} onClick={() => setCartSort(cartSort === 'date_desc' ? 'date_asc' : 'date_desc')}>
                        Last Updated {cartSort === 'date_desc' ? '↓' : cartSort === 'date_asc' ? '↑' : ''}
                      </th>
                      <th style={{ padding: '10px 12px', cursor: 'pointer' }} onClick={() => setCartSort(cartSort === 'customer_asc' ? 'customer_desc' : 'customer_asc')}>
                        Customer {cartSort === 'customer_asc' ? '↑' : cartSort === 'customer_desc' ? '↓' : ''}
                      </th>
                      <th style={{ padding: '10px 12px' }}>Cart Details</th>
                      <th style={{ padding: '10px 12px', cursor: 'pointer' }} onClick={() => setCartSort(cartSort === 'value_asc' ? 'value_desc' : 'value_asc')}>
                        Cart Value {cartSort === 'value_asc' ? '↑' : cartSort === 'value_desc' ? '↓' : ''}
                      </th>
                      <th style={{ padding: '10px 12px', cursor: 'pointer' }} onClick={() => setCartSort(cartSort === 'recovery_asc' ? 'recovery_desc' : 'recovery_asc')}>
                        Recovery Status {cartSort === 'recovery_asc' ? '↑' : cartSort === 'recovery_desc' ? '↓' : ''}
                      </th>
                      <th style={{ padding: '10px 12px', textAlign: 'right' }}>Actions</th>
                    </tr>
                  </thead>
                  <tbody>
                    {(() => {
                      let filteredCarts = abandonedCarts.filter(c => {
                        let matchContact = true;
                        if (cartFilterContact === 'has_email') matchContact = !!c.customer_email;
                        if (cartFilterContact === 'has_phone') matchContact = !!c.customer_phone;
                        if (cartFilterContact === 'actionable') matchContact = !!c.customer_email || !!c.customer_phone;
                        if (cartFilterContact === 'none') matchContact = !c.customer_email && !c.customer_phone;
                        
                        let matchStatus = true;
                        if (cartFilterStatus === 'not_contacted') matchStatus = !getCartRecoveryStatus(c) || getCartRecoveryStatus(c) === 'not_contacted';
                        if (cartFilterStatus === 'contacted') matchStatus = getCartRecoveryStatus(c) === 'contacted_email' || getCartRecoveryStatus(c) === 'contacted_whatsapp';
                        if (cartFilterStatus === 'recovered') matchStatus = getCartRecoveryStatus(c) === 'recovered';
                        
                        let matchValue = true;
                        const val = getCartValue(c);
                        if (cartFilterValue === 'high') matchValue = val >= 100;
                        if (cartFilterValue === 'low') matchValue = val < 100;
                        
                        return matchContact && matchStatus && matchValue;
                      });

                      let sortedCarts = [...filteredCarts];
                      if (cartSort === 'value_asc' || cartSort === 'value_desc') {
                        sortedCarts.sort((a, b) => {
                          const valA = getCartValue(a);
                          const valB = getCartValue(b);
                          return cartSort === 'value_asc' ? valA - valB : valB - valA;
                        });
                      } else if (cartSort === 'recovery_asc' || cartSort === 'recovery_desc') {
                        sortedCarts.sort((a, b) => {
                          const statusA = getCartRecoveryStatus(a) || '';
                          const statusB = getCartRecoveryStatus(b) || '';
                          const res = statusA.localeCompare(statusB);
                          if (res !== 0) return cartSort === 'recovery_asc' ? res : -res;
                          
                          // Secondary sort: automatically float carts with emails/phones to the top of their status group
                          const hasContactA = (a.email || a.phone) ? 1 : 0;
                          const hasContactB = (b.email || b.phone) ? 1 : 0;
                          return hasContactB - hasContactA;
                        });
                      } else if (cartSort === 'customer_asc' || cartSort === 'customer_desc') {
                        sortedCarts.sort((a, b) => {
                          const contactA = (a.email || '') + (a.phone || '');
                          const contactB = (b.email || '') + (b.phone || '');
                          const res = contactA.localeCompare(contactB);
                          return cartSort === 'customer_asc' ? res : -res;
                        });
                      } else {
                        sortedCarts.sort((a, b) => {
                          const timeA = new Date(a.updated_at).getTime();
                          const timeB = new Date(b.updated_at).getTime();
                          return cartSort === 'date_desc' ? timeB - timeA : timeA - timeB;
                        });
                      }
                      return sortedCarts.map((acart, index) => {
                      const totalQty = acart.cart_data ? acart.cart_data.reduce((acc, item) => acc + (item.qty || 0), 0) : 0;
                      
                      return (
                        <tr key={acart.session_id}>
                          <td data-label="Select" style={{ padding: '10px 12px', textAlign: 'center' }}>
                            <input 
                              type="checkbox" 
                              checked={selectedCartIds.includes(acart.session_id)} 
                              onClick={(e) => {
                                const checked = e.target.checked;
                                const shiftKey = e.shiftKey;
                                handleSelectCart(acart.session_id, checked, shiftKey, index);
                              }}
                              onChange={() => {}}
                              style={{ cursor: 'pointer', transform: 'scale(1.1)' }}
                            />
                          </td>
                          <td data-label="Last Updated" style={{ padding: '10px 12px', fontSize: '0.85rem', color: '#cbd5e1' }}>
                            {new Date(acart.last_updated).toLocaleString(undefined, {month: 'short', day: 'numeric', hour: '2-digit', minute:'2-digit'})}
                          </td>
                          <td data-label="Customer" style={{ padding: '10px 12px' }}>
                            <div style={{ display: 'flex', flexDirection: 'column', gap: '2px' }}>
                              <span style={{ fontWeight: 'bold', color: '#f8fafc', fontSize: '0.85rem' }}>
                                {acart.customer_name || 'Anonymous User'}
                              </span>
                              {acart.customer_phone ? (
                                <span style={{ fontSize: '0.75rem', color: '#94a3b8' }}>
                                  💬 {acart.customer_phone}
                                </span>
                              ) : acart.customer_email ? (
                                <span style={{ fontSize: '0.75rem', color: '#94a3b8' }}>
                                  ✉️ {acart.customer_email}
                                </span>
                              ) : null}
                            </div>
                          </td>
                          <td data-label="Cart Details" style={{ padding: '10px 12px' }}>
                            <button 
                              onClick={() => setSelectedCartDetails(acart)}
                              style={{ 
                                background: 'rgba(56, 189, 248, 0.1)', 
                                border: '1px solid rgba(56, 189, 248, 0.2)', 
                                color: '#38bdf8', 
                                padding: '4px 10px', 
                                borderRadius: '20px', 
                                fontSize: '0.75rem', 
                                fontWeight: 'bold',
                                cursor: 'pointer',
                                display: 'inline-flex',
                                alignItems: 'center',
                                gap: '6px'
                              }}
                            >
                              🛒 {totalQty} {totalQty === 1 ? 'Item' : 'Items'}
                            </button>
                          </td>
                          <td data-label="Cart Value" style={{ padding: '10px 12px', fontSize: '0.9rem', fontWeight: 'bold', color: '#4ade80' }}>
                            ${getCartValue(acart).toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 })}
                          </td>
                          <td data-label="Recovery Status" style={{ padding: '10px 12px' }}>
                            <div style={{ display: 'flex', flexDirection: 'column', gap: '6px', alignItems: 'flex-start' }}>
                              {acart.customer_email && (
                                <span style={{ 
                                  background: acart.recovery_email_sent ? 'rgba(16, 185, 129, 0.15)' : 'rgba(148, 163, 184, 0.15)',
                                  color: acart.recovery_email_sent ? '#34d399' : '#94a3b8',
                                  padding: '4px 10px',
                                  borderRadius: '20px',
                                  fontSize: '0.75rem',
                                  fontWeight: 'bold',
                                  display: 'inline-flex',
                                  alignItems: 'center',
                                  gap: '4px'
                                }}>
                                  ✉️ {acart.recovery_email_sent ? 'Email Sent' : 'Email Not Sent'}
                                </span>
                              )}
                              {acart.customer_phone && (
                                <span style={{ 
                                  background: acart.recovery_whatsapp_sent ? 'rgba(34, 197, 94, 0.15)' : 'rgba(148, 163, 184, 0.15)',
                                  color: acart.recovery_whatsapp_sent ? '#4ade80' : '#94a3b8',
                                  padding: '4px 10px',
                                  borderRadius: '20px',
                                  fontSize: '0.75rem',
                                  fontWeight: 'bold',
                                  display: 'inline-flex',
                                  alignItems: 'center',
                                  gap: '4px'
                                }}>
                                  💬 {acart.recovery_whatsapp_sent ? 'WhatsApp Sent' : 'WA Not Sent'}
                                </span>
                              )}
                              {!acart.customer_email && !acart.customer_phone && (
                                <span style={{ 
                                  background: 'rgba(239, 68, 68, 0.1)',
                                  color: '#f87171',
                                  padding: '4px 10px',
                                  borderRadius: '20px',
                                  fontSize: '0.75rem',
                                  fontWeight: 'bold',
                                  display: 'inline-block'
                                }}>
                                  🚫 No Contact Info
                                </span>
                              )}
                            </div>
                          </td>
                            <td data-label="Actions" style={{ padding: '10px 12px' }}>
                              <div className="admin-card-actions">
                                <button 
                                  className="admin-btn" 
                                  onClick={() => setSelectedCartDetails(acart)}
                                  style={{ padding: '6px 12px', fontSize: '0.8rem', background: '#3b82f6', color: '#fff', border: 'none', borderRadius: '6px', fontWeight: 'bold' }}
                                >
                                  Details
                                </button>
                                
                                {acart.customer_email && (
                                  <button
                                    onClick={() => handleSendRecoveryEmail(acart)}
                                    disabled={sendingRecoveryEmail[acart.session_id]}
                                    className="admin-btn admin-cta-btn"
                                    style={{ 
                                      padding: '6px 12px', 
                                      fontSize: '0.8rem', 
                                      background: '#0ea5e9', 
                                      border: 'none', 
                                      color: '#fff', 
                                      borderRadius: '6px',
                                      fontWeight: 'bold'
                                    }}
                                  >
                                    {sendingRecoveryEmail[acart.session_id] ? 'Sending...' : '✉️ Recover Email'}
                                  </button>
                                )}
                                
                                {acart.customer_phone && (
                                  <button
                                    onClick={() => openWhatsAppComposer({ 
                                      name: acart.customer_name, 
                                      phone: acart.customer_phone, 
                                      cartItems: acart.cart_data || [], 
                                      session_id: acart.session_id 
                                    })}
                                    className="admin-btn admin-cta-btn"
                                    style={{ 
                                      padding: '6px 12px', 
                                      fontSize: '0.8rem', 
                                      background: '#10b981', 
                                      border: 'none', 
                                      color: '#fff', 
                                      borderRadius: '6px', 
                                      display: 'inline-flex', 
                                      alignItems: 'center', 
                                      gap: '4px', 
                                      fontWeight: 'bold',
                                      cursor: 'pointer'
                                    }}
                                  >
                                    💬 Recover WA
                                  </button>
                                )}

                                {!acart.customer_email && !acart.customer_phone && (
                                  <button
                                    onClick={() => setSelectedCartDetails(acart)}
                                    className="admin-btn admin-cta-btn"
                                    style={{ 
                                      padding: '6px 12px', 
                                      fontSize: '0.8rem', 
                                      background: '#475569', 
                                      border: 'none', 
                                      color: '#fff', 
                                      borderRadius: '6px',
                                      fontWeight: 'bold'
                                    }}
                                  >
                                    ✏️ Add Info
                                  </button>
                                )}
                                
                                <button
                                  onClick={() => handleDeleteCart(acart.session_id)}
                                  className="admin-btn"
                                  style={{ padding: '6px 12px', fontSize: '0.8rem', background: 'rgba(239, 68, 68, 0.1)', border: '1px solid rgba(239, 68, 68, 0.2)', color: '#ef4444', borderRadius: '6px' }}
                                >
                                  Delete
                                </button>
                              </div>
                            </td>
                        </tr>
                      );
                    })})()}
                  </tbody>
                </table>
              </div>
            )}
          </div>
        )}

        {/* TAB: REVIEWS MODERATION */}
        