-- Rewrite the ten GLP-1 product descriptions for the card processor.
--
-- All ten carried the same paragraph, and the rename that made these products
-- "GLP-1" never touched it. It opened "Retatrutide is an investigational
-- triple-receptor agonist ... under development for obesity and type 2
-- diabetes", cited "patients losing up to 24% of body weight", and closed with
-- a once-weekly subcutaneous schedule and titration advice.
--
-- Four separate problems in one paragraph: the superseded name, two named
-- diseases, a promised body outcome, and dosing guidance the About page
-- explicitly says we do not give. The Spanish said the same in "la retatrutida",
-- which no find-and-replace on the English spelling would ever have caught.
--
-- What replaces it states what the material is, how it is supplied, how to
-- store it, and what it is not for. The receptor mechanism stays: that is a
-- fact about the molecule, not a claim about what it does for a buyer.
--
-- Safe to run more than once.

UPDATE public.products SET description_en = 'GLP-1 is a synthetic peptide that acts as an agonist at the GLP-1, GIP and glucagon receptors. Supplied as a lyophilised powder, 5mg per vial, with Certificate of Analysis documentation available for the batch. Store sealed vials refrigerated at 2–8 °C, away from light. Sold strictly as a research material for laboratory use only — not for human or animal consumption, and not for diagnostic or therapeutic use. We do not provide dosing, administration or preparation guidance.', description_es = 'GLP-1 es un péptido sintético que actúa como agonista de los receptores GLP-1, GIP y glucagón. Se suministra como polvo liofilizado, 5mg por vial, con documentación de Certificado de Análisis disponible para el lote. Conserve los viales sellados refrigerados entre 2 y 8 °C, protegidos de la luz. Se vende estrictamente como material de investigación para uso exclusivo de laboratorio: no apto para consumo humano ni animal, ni para uso diagnóstico o terapéutico. No brindamos orientación sobre dosificación, administración ni preparación.' WHERE product = 'GLP-1 5mg';
UPDATE public.products SET description_en = 'GLP-1 is a synthetic peptide that acts as an agonist at the GLP-1, GIP and glucagon receptors. Supplied as a lyophilised powder, 10mg per vial, with Certificate of Analysis documentation available for the batch. Store sealed vials refrigerated at 2–8 °C, away from light. Sold strictly as a research material for laboratory use only — not for human or animal consumption, and not for diagnostic or therapeutic use. We do not provide dosing, administration or preparation guidance.', description_es = 'GLP-1 es un péptido sintético que actúa como agonista de los receptores GLP-1, GIP y glucagón. Se suministra como polvo liofilizado, 10mg por vial, con documentación de Certificado de Análisis disponible para el lote. Conserve los viales sellados refrigerados entre 2 y 8 °C, protegidos de la luz. Se vende estrictamente como material de investigación para uso exclusivo de laboratorio: no apto para consumo humano ni animal, ni para uso diagnóstico o terapéutico. No brindamos orientación sobre dosificación, administración ni preparación.' WHERE product = 'GLP-1 10mg';
UPDATE public.products SET description_en = 'GLP-1 is a synthetic peptide that acts as an agonist at the GLP-1, GIP and glucagon receptors. Supplied as a lyophilised powder, 12mg per vial, with Certificate of Analysis documentation available for the batch. Store sealed vials refrigerated at 2–8 °C, away from light. Sold strictly as a research material for laboratory use only — not for human or animal consumption, and not for diagnostic or therapeutic use. We do not provide dosing, administration or preparation guidance.', description_es = 'GLP-1 es un péptido sintético que actúa como agonista de los receptores GLP-1, GIP y glucagón. Se suministra como polvo liofilizado, 12mg por vial, con documentación de Certificado de Análisis disponible para el lote. Conserve los viales sellados refrigerados entre 2 y 8 °C, protegidos de la luz. Se vende estrictamente como material de investigación para uso exclusivo de laboratorio: no apto para consumo humano ni animal, ni para uso diagnóstico o terapéutico. No brindamos orientación sobre dosificación, administración ni preparación.' WHERE product = 'GLP-1 12mg';
UPDATE public.products SET description_en = 'GLP-1 is a synthetic peptide that acts as an agonist at the GLP-1, GIP and glucagon receptors. Supplied as a lyophilised powder, 15mg per vial, with Certificate of Analysis documentation available for the batch. Store sealed vials refrigerated at 2–8 °C, away from light. Sold strictly as a research material for laboratory use only — not for human or animal consumption, and not for diagnostic or therapeutic use. We do not provide dosing, administration or preparation guidance.', description_es = 'GLP-1 es un péptido sintético que actúa como agonista de los receptores GLP-1, GIP y glucagón. Se suministra como polvo liofilizado, 15mg por vial, con documentación de Certificado de Análisis disponible para el lote. Conserve los viales sellados refrigerados entre 2 y 8 °C, protegidos de la luz. Se vende estrictamente como material de investigación para uso exclusivo de laboratorio: no apto para consumo humano ni animal, ni para uso diagnóstico o terapéutico. No brindamos orientación sobre dosificación, administración ni preparación.' WHERE product = 'GLP-1 15mg';
UPDATE public.products SET description_en = 'GLP-1 is a synthetic peptide that acts as an agonist at the GLP-1, GIP and glucagon receptors. Supplied as a lyophilised powder, 20mg per vial, with Certificate of Analysis documentation available for the batch. Store sealed vials refrigerated at 2–8 °C, away from light. Sold strictly as a research material for laboratory use only — not for human or animal consumption, and not for diagnostic or therapeutic use. We do not provide dosing, administration or preparation guidance.', description_es = 'GLP-1 es un péptido sintético que actúa como agonista de los receptores GLP-1, GIP y glucagón. Se suministra como polvo liofilizado, 20mg por vial, con documentación de Certificado de Análisis disponible para el lote. Conserve los viales sellados refrigerados entre 2 y 8 °C, protegidos de la luz. Se vende estrictamente como material de investigación para uso exclusivo de laboratorio: no apto para consumo humano ni animal, ni para uso diagnóstico o terapéutico. No brindamos orientación sobre dosificación, administración ni preparación.' WHERE product = 'GLP-1 20mg';
UPDATE public.products SET description_en = 'GLP-1 is a synthetic peptide that acts as an agonist at the GLP-1, GIP and glucagon receptors. Supplied as a lyophilised powder, 24mg per vial, with Certificate of Analysis documentation available for the batch. Store sealed vials refrigerated at 2–8 °C, away from light. Sold strictly as a research material for laboratory use only — not for human or animal consumption, and not for diagnostic or therapeutic use. We do not provide dosing, administration or preparation guidance.', description_es = 'GLP-1 es un péptido sintético que actúa como agonista de los receptores GLP-1, GIP y glucagón. Se suministra como polvo liofilizado, 24mg por vial, con documentación de Certificado de Análisis disponible para el lote. Conserve los viales sellados refrigerados entre 2 y 8 °C, protegidos de la luz. Se vende estrictamente como material de investigación para uso exclusivo de laboratorio: no apto para consumo humano ni animal, ni para uso diagnóstico o terapéutico. No brindamos orientación sobre dosificación, administración ni preparación.' WHERE product = 'GLP-1 24mg';
UPDATE public.products SET description_en = 'GLP-1 is a synthetic peptide that acts as an agonist at the GLP-1, GIP and glucagon receptors. Supplied as a lyophilised powder, 30mg per vial, with Certificate of Analysis documentation available for the batch. Store sealed vials refrigerated at 2–8 °C, away from light. Sold strictly as a research material for laboratory use only — not for human or animal consumption, and not for diagnostic or therapeutic use. We do not provide dosing, administration or preparation guidance.', description_es = 'GLP-1 es un péptido sintético que actúa como agonista de los receptores GLP-1, GIP y glucagón. Se suministra como polvo liofilizado, 30mg por vial, con documentación de Certificado de Análisis disponible para el lote. Conserve los viales sellados refrigerados entre 2 y 8 °C, protegidos de la luz. Se vende estrictamente como material de investigación para uso exclusivo de laboratorio: no apto para consumo humano ni animal, ni para uso diagnóstico o terapéutico. No brindamos orientación sobre dosificación, administración ni preparación.' WHERE product = 'GLP-1 30mg';
UPDATE public.products SET description_en = 'GLP-1 is a synthetic peptide that acts as an agonist at the GLP-1, GIP and glucagon receptors. Supplied as a lyophilised powder, 40mg per vial, with Certificate of Analysis documentation available for the batch. Store sealed vials refrigerated at 2–8 °C, away from light. Sold strictly as a research material for laboratory use only — not for human or animal consumption, and not for diagnostic or therapeutic use. We do not provide dosing, administration or preparation guidance.', description_es = 'GLP-1 es un péptido sintético que actúa como agonista de los receptores GLP-1, GIP y glucagón. Se suministra como polvo liofilizado, 40mg por vial, con documentación de Certificado de Análisis disponible para el lote. Conserve los viales sellados refrigerados entre 2 y 8 °C, protegidos de la luz. Se vende estrictamente como material de investigación para uso exclusivo de laboratorio: no apto para consumo humano ni animal, ni para uso diagnóstico o terapéutico. No brindamos orientación sobre dosificación, administración ni preparación.' WHERE product = 'GLP-1 40mg';
UPDATE public.products SET description_en = 'GLP-1 is a synthetic peptide that acts as an agonist at the GLP-1, GIP and glucagon receptors. Supplied as a lyophilised powder, 50mg per vial, with Certificate of Analysis documentation available for the batch. Store sealed vials refrigerated at 2–8 °C, away from light. Sold strictly as a research material for laboratory use only — not for human or animal consumption, and not for diagnostic or therapeutic use. We do not provide dosing, administration or preparation guidance.', description_es = 'GLP-1 es un péptido sintético que actúa como agonista de los receptores GLP-1, GIP y glucagón. Se suministra como polvo liofilizado, 50mg por vial, con documentación de Certificado de Análisis disponible para el lote. Conserve los viales sellados refrigerados entre 2 y 8 °C, protegidos de la luz. Se vende estrictamente como material de investigación para uso exclusivo de laboratorio: no apto para consumo humano ni animal, ni para uso diagnóstico o terapéutico. No brindamos orientación sobre dosificación, administración ni preparación.' WHERE product = 'GLP-1 50mg';
UPDATE public.products SET description_en = 'GLP-1 is a synthetic peptide that acts as an agonist at the GLP-1, GIP and glucagon receptors. Supplied as a lyophilised powder, 60mg per vial, with Certificate of Analysis documentation available for the batch. Store sealed vials refrigerated at 2–8 °C, away from light. Sold strictly as a research material for laboratory use only — not for human or animal consumption, and not for diagnostic or therapeutic use. We do not provide dosing, administration or preparation guidance.', description_es = 'GLP-1 es un péptido sintético que actúa como agonista de los receptores GLP-1, GIP y glucagón. Se suministra como polvo liofilizado, 60mg por vial, con documentación de Certificado de Análisis disponible para el lote. Conserve los viales sellados refrigerados entre 2 y 8 °C, protegidos de la luz. Se vende estrictamente como material de investigación para uso exclusivo de laboratorio: no apto para consumo humano ni animal, ni para uso diagnóstico o terapéutico. No brindamos orientación sobre dosificación, administración ni preparación.' WHERE product = 'GLP-1 60mg';

-- Nothing should come back.
SELECT product FROM public.products
 WHERE description_en ILIKE '%retatrutid%' OR description_es ILIKE '%retatrutid%';
